# Generated by Django 6.0.4 on 2026-05-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Student_ID', models.CharField(max_length=10)),
                ('Year_Group', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Code', models.CharField(max_length=10)),
                ('Assessment_Period', models.CharField(max_length=5)),
                ('Course_Code', models.CharField(max_length=10)),
            ],
        ),
    ]
