# Generated by Django 4.2.29 on 2026-05-17 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='Course_Code',
        ),
        migrations.AddField(
            model_name='units',
            name='Course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CourseCode', to='MyApp1.courses'),
            preserve_default=False,
        ),
    ]
