# Generated by Django 4.2.29 on 2026-05-17 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0002_remove_units_course_code_units_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp1.courses'),
        ),
    ]
