# Generated by Django 6.0.4 on 2026-05-13 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0004_student_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ID',
            new_name='Student_ID',
        ),
    ]
