# Generated by Django 6.0.2 on 2026-02-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Area',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='Name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
